volumes:
  pg_chat_volume:

services:

  pg_chat_server_dev:
    image: postgres:14-alpine3.17
    profiles:
      - dev
    environment:
      - "POSTGRES_DB=chat"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=1234"
    ports:
      - "${PG_PORT_OUTER}:${PG_PORT}"
    volumes:
      - pg_chat_volume:/var/lib/postgresql/data

  chat_app_dev:
    depends_on:
      - pg_chat_server_dev
    profiles:
      - dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:${GRPC_PORT}"