volumes:
  pg_chat_volume:
  pg_chat_volume_local:

services:

  pg_chat_server_dev:
    image: postgres:14-alpine3.17
    container_name: pg_chat_server_dev
    profiles:
      - dev
    env_file:
      - dev.env
    environment:
      - "POSTGRES_DB=chat"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=1234"
    ports:
      - "${PG_PORT_OUTER}:${PG_PORT}"
    volumes:
      - pg_chat_volume:/var/lib/postgresql/data

  chat_server_dev:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE}
    depends_on:
      - pg_chat_server_dev
    profiles:
      - dev
    env_file:
      - dev.env
    environment:
      - "CONFIG_FILE=dev.env"
    ports:
      - "8082:${GRPC_PORT}"

  migrations_dev:
    container_name: ${MIGRATION_CONTAINER_NAME}
    image: ${MIGRATION_IMAGE_NAME}
    profiles:
      - dev
    restart: on-failure
    environment:
      DB_HOST: pg_chat_server_dev
    env_file:
      - dev.env
    depends_on:
      - pg_chat_server_dev


  pg_chat_server_local:
    image: postgres:14-alpine3.17
    profiles:
      - local
    env_file:
      - local.env
    environment:
      - "POSTGRES_DB=chat"
      - "POSTGRES_USER=user"
      - "POSTGRES_PASSWORD=1234"
    ports:
      - "${PG_PORT_OUTER}:${PG_PORT}"
    volumes:
      - pg_chat_volume_local:/var/lib/postgresql/data

  chat_server_local:
    depends_on:
      - pg_chat_server_local
    profiles:
      - local
    env_file:
      - local.env
    environment:
      - "CONFIG_FILE=local.env"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:${GRPC_PORT}"


  pg_chat_server_test:
    image: postgres:14-alpine3.17
    profiles:
      - test
    env_file:
      - test.env
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT_OUTER}:5432"
    volumes:
      - pg_chat_volume_local:/var/lib/postgresql/data

